output "vpc_id" {
    description = "Zookeeper VPC ID"
    value = aws_vpc.zk-test.id
}

/* Using a for loop to iterate over map object which is generated by EC2 for_each meta */

output "instance_public_dns" {
    description = "Zookeeper EC2 instance Public DNS"
    value = [ for ec2_instance in aws_instance.zk_ec2: ec2_instance.public_dns ]
}

output "instance_public_ip" {
    description = "Zookeeper EC2 instance Public IP"
    value = [ for ec2_instance in aws_instance.zk_ec2: ec2_instance.public_ip ]
}
